gameproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from gamehost import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': r'/home/'}, name="logout"),
    url(r'^$', views.homeview, name="homeview"),
    url(r'^home/$', views.homeview, name="homeview"),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/profile/(?P<user_id>[0-9]+)/$', views.profile),
    url(r'^register/$', views.register),
    url(r'^activate/(?P<key>.*)/?$', views.activate),
    url(r'^game/(?P<game_id>[0-9]+)/$', views.game),
    url(r'^add_game/$', views.add_game),
    url(r'^addscore/$', views.add_highscore),
    url(r'^savegame/$', views.save_game),
    url(r'^loadgame/$', views.load_game),
    url(r'^editgame/(?P<game_id>[0-9]+)/$', views.edit_game),
    url(r'^deletegame/(?P<game_id>[0-9]+)/$', views.delete_game),
    url(r'^add_to_basket/(?P<game_id>[0-9]+)/$', views.add_to_basket, name="add_to_basket"),
    url(r'^remove_from_basket/(?P<game_id>[0-9]+)/$', views.remove_from_basket, name="remove_from_basket"),
    url(r'^basket/$', views.basket, name="basket"),
    url(r'^purchased_games/(?P<user_id>[0-9]+)/$', views.purchased_games),
    url(r'^games/$', views.games),
    url(r'^checkout/$', views.checkout, name="checkout"),
    url(r'^checkout/success/$', views.payment_success, name="payment_success"),
    url(r'^checkout/cancel/$', views.payment_cancel, name="payment_cancel"),
    url(r'^checkout/error/$', views.payment_error, name="payment_error"),
    url(r'^checkout/lost/$', views.payment_lost, name="payment_lost"),
    url(r'', include('social_django.urls', namespace='social')),
]

gamehost/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.files.storage import get_storage_class
from django.conf import settings
import json

# Create your models here.


class SiteUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    developer_status = models.BooleanField(default=False)
    registration_date = models.DateField(auto_now=False, auto_now_add=True)

    def get_transactions(self):
        transactions = Transaction.objects.filter(player=self, payment__status=Payment.SUCCESS)
        return transactions

    def has_purchased_game(self, game):
        query = Transaction.objects.filter(player=self, game=game, payment__status=Payment.SUCCESS)
        if query.count() >= 1:
            return True
        else:
            return False


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        SiteUser.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_siteuser(sender, instance, **kwards):
    instance.siteuser.save()


class Game(models.Model):
    name = models.TextField()

    UNDEFINED = 'undefined'
    STRATEGY = 'strategy'
    SHOOTING = 'shooting'
    ARCADE = 'arcade'
    ADVENTURE = 'adventure'
    CATEGORY_CHOICES = (
        (UNDEFINED, 'undefined'),
        (STRATEGY, 'strategy'),
        (SHOOTING, 'shooting'),
        (ARCADE, 'arcade'),
        (ADVENTURE, 'adventure')
    )
    category = models.TextField(
        choices=CATEGORY_CHOICES,
        default=UNDEFINED
    )
    developer = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    src = models.URLField()
    price = models.DecimalField(decimal_places=2, max_digits=6)
    publish_date = models.DateField(auto_now=False, auto_now_add=True)
    thumbnail = models.URLField(
        null=True,
        blank=True
    )

    def addHighscore(self, score, user):
        # Remove comments if the amount of highscores is to be limited.
        # player_scores = self.highscore_set.filter(
        #    player=user).order_by('score')
        # if player_scores.count() >= 5:
        #    if (score > player_scores.first().score):
        #        player_scores.first().delete()
        #        Highscore.objects.create(player=user, game=self, score=score)
        # else:
            Highscore.objects.create(player=user, game=self, score=score)

    def saveGame(self, user, data):
        try:
            save = Savedata.objects.get(player=user, game=self)
            save.data = data
            save.save()
            return save
        except Savedata.DoesNotExist:
            save = Savedata()
            save.player = user
            save.game = self
            save.data = data
            save.save()
            return save

    def loadGame(self, user):
        try:
            load = Savedata.objects.get(player=user, game=self)
            data = json.loads(load.data)
            return data
        except Savedata.DoesNotExist:
            msg = "No data found"
            return msg

    def get_transactions(self):
        return Transaction.objects.filter(game=self, payment__status=Payment.SUCCESS)

    def get_highscores(self, user, own):
        if (own):
            query_set = Highscore.objects.filter(game=self, user=user)
        else:
            query_set = Highscore.objects.filter(
                game=self).order_by('-score')[:5]
        if query_set.count() > 5:
            return query_set[:5]
        else:
            return query_set

    def __str__(self):
        return "{}".format(self.name)


class Highscore(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    player = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    date = models.DateField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return "{}".format(self.score)


class Payment(models.Model):
    # Failed payments will be deleted
    IN_PROGRESS = 'in_progress'
    SUCCESS = 'success'
    STATUS_CHOICES = (
        (IN_PROGRESS, 'in_progress'),
        (SUCCESS, 'success'),
    )
    status = models.TextField(
        choices=STATUS_CHOICES,
        default=IN_PROGRESS
    )
    date = models.DateField(auto_now=False, auto_now_add=True)
    total = models.DecimalField(decimal_places=2, max_digits=9)

def default_payment():
    payment = Payment.objects.create(total=0, status=Payment.SUCCESS)
    return payment.id

class Transaction(models.Model):
    player = models.ForeignKey(SiteUser)
    game = models.ForeignKey(Game)
    price = models.DecimalField(decimal_places=2, max_digits=6)
    payment = models.ForeignKey(Payment, default=default_payment, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.game)


class Savedata(models.Model):
    player = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    data = models.TextField()
    date = models.DateField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return "{}".format(self.data)

gamehost/forms.py
from django.forms import ModelForm, TextInput, Select
from django.contrib.auth.models import User
from gamehost.models import SiteUser, Game
from django import forms

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

class SiteUserForm(ModelForm):
    class Meta:
        model = SiteUser
        exclude = ['user']

class GameForm(ModelForm):
    class Meta:
        model = Game
        exclude = ['developer']
        widgets = {
            'name': TextInput(),
            'category': Select()
        }
        labels = {
            'src': 'Game source URL',
            'thumbnail': 'Game thumbnail URL',
        }

gamehost/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse
from gamehost.models import Game, Highscore, Savedata, Transaction, Payment
from gamehost.forms import UserForm, SiteUserForm, GameForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from datetime import timedelta
from django.core.signing import TimestampSigner, SignatureExpired
from django.core import signing, mail

import json, datetime
from hashlib import md5

PAYMENT_ID = "sid271828"
PAYMENT_KEY = "9846b7da3d25fc3b6ece0b753a47b099"

# Create your views here.

# Just to test how the views worked again.
def homeview(request):
    #game_list = Game.objects.all()
    return render(request, 'home.html', {})


@login_required(login_url='/login/')
def profile(request, user_id):
    try:
        profile = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        raise Http404("Profile does not exist")
    else:
        if int(request.user.id) is not int(user_id):
            return HttpResponse("Permission denied")
        else:
            if profile.siteuser.developer_status:
                #Get sales statistics for the developer
                games = Game.objects.filter(developer=profile.siteuser)
                #trans = []
                totals = {}
                datelist = {}
                now = datetime.datetime.today()
                today = datetime.date(now.year, now.month, now.day)
                i = 0
                for g in games:

                    transactions = Transaction.objects.filter(game=g, payment__status=Payment.SUCCESS)
                    totals.update({g.name: transactions.count()})
                    #trans.append(transactions)

                    dates = []
                    day_count = (today - g.publish_date).days + 1
                    for single_date in (g.publish_date + timedelta(n) for n in range(day_count)):
                        daily_data = []
                        daily_data.append(single_date.isoformat())
                        dailytrans = transactions.filter(payment__date=single_date).count()
                        daily_data.append(dailytrans)
                        dates.append(daily_data)
                    datelist.update({g.name: dates})

                datelistj = json.dumps(datelist)
                return render(request, 'profile.html', {'profile': profile, 'games': games, 'totalSalesList': totals, 'datelistj': datelistj})#, 'transactions': transactions})
            else:
                return render(request, 'profile.html', {'profile': profile})

@login_required(login_url='/login/')
def add_game(request):
    if request.user.siteuser.developer_status == False:
        return render(request, 'message.html', {'message': 'Please register as a developer if you want to add games.'})
    elif request.method == 'POST':
        game_form = GameForm(request.POST)

        if game_form.is_valid():
            newgame = game_form.save(commit=False)
            newgame.developer = request.user.siteuser
            newgame.save()
            game_form.save_m2m() #save the many-to-many data for the form
            return render(request, 'message.html', {'message': 'Your game was added!'})
    else:
        game_form = GameForm()

    return render(request, 'add_game.html', {'game_form': game_form })


@login_required(login_url='/login/')
def game(request, game_id):
    try:
        game = Game.objects.get(pk=game_id)
    except Game.DoesNotExist:
        raise Http404("Game not found!")
    else:
        has_purchased = request.user.siteuser.has_purchased_game(game)
        highscores = game.get_highscores(request.user.siteuser, False)
        return render(request, 'game.html', {'game': game,
                                             'has_purchased': has_purchased,
                                             'highscores': highscores,
                                             'user': request.user})

def games(request):
    genre = request.GET.get('genre')

    if genre == "all":
        games = Game.objects.all()
        return render(request, 'games.html', {'games': games})
    else:
        games = Game.objects.filter(category=genre)
        return render(request, 'games.html', {'games': games})

@login_required(login_url='/login/')
def edit_game(request, game_id):
    try:
        game = Game.objects.get(pk=game_id)
    except Game.DoesNotExist:
        raise Http404("Game not found!")
    else:
        if request.method == 'POST':
            game_form = GameForm(request.POST)

            if game_form.is_valid() and (int(request.user.id) is int(game.developer.user.id)):
                game = Game.objects.get(pk=game_id)
                game.name = game_form.cleaned_data['name']
                game.category = game_form.cleaned_data['category']
                game.price = game_form.cleaned_data['price']
                game.src = game_form.cleaned_data['src']
                game.thumbnail = game_form.cleaned_data['thumbnail']
                game.save()
                return render(request,
                              'message.html', {'message': 'Changes saved'})
            else:
                return HttpResponse('Something went wrong trying to edit')
        else:
            if int(request.user.id) is not int(game.developer.user.id):
                return HttpResponse("Permission denied.")
            else:
                data = {'name': game.name, 'category': game.category,
                        'price': game.price, 'src': game.src,
                        'thumbnail': game.thumbnail}
                form = GameForm(initial=data)
                return render(request,
                              'edit_game.html',
                              {'game_form': form, 'game': game})


@login_required(login_url='/login/')
def delete_game(request, game_id):
    try:
        game = Game.objects.get(pk=game_id)
    except Game.DoesNotExist:
        raise Http404("Game not found!")
    else:
        if request.method == "POST":
            if int(request.user.id) is int(game.developer.user.id):
                game.delete()
                return HttpResponse("Game deleted")
            else:
                return HttpResponse("Permission Denied")
        else:
            return render(request,
                          'delete_game.html',
                          {'object': game})

@login_required(login_url='/login/')
def purchased_games(request, user_id):
    try:
        user_profile = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        raise Http404("User not found.")
    else:
        if int(request.user.id) is not int(user_id):
            return HttpResponse("Permission denied.")
        else:
            return render(
                            request,
                            'purchased_games.html',
                            {'user': user_profile})

def add_highscore(request):
    score = Highscore()
    game = Game.objects.get(name=request.GET.get('game'))
    score.game = game
    user = User.objects.get(username=request.GET.get('user'))
    score.player = user.siteuser
    score.score = request.GET.get('score')
    score.save()
    highscores = game.get_highscores(user.siteuser, False)
    return render(request, 'highscore.html', {'highscores': highscores})


def save_game(request):
    game = Game.objects.get(name=request.GET.get('game'))
    user = User.objects.get(username=request.GET.get('user'))
    data = request.GET.get('game_state')
    save = game.saveGame(user.siteuser, data)
    date = save.date.strftime("%B %d, %Y")
    return HttpResponse('Last saved ' + date)


def load_game(request):
    game = Game.objects.get(name=request.GET.get('game'))
    user = User.objects.get(username=request.GET.get('user'))
    msg = game.loadGame(user.siteuser)
    if msg is not "No data found":
        return JsonResponse({'messageType': 'LOAD', 'gameState': msg})
    else:
        return JsonResponse({'messageType': 'ERROR',
                            'info': 'Gamestate could not be loaded.'})


def register(request):
    if request.user.is_authenticated():
        return redirect(homeview)
    # if this is a POST request we need to process the forms' data and register the user
    if request.method == 'POST':
        user_form = UserForm(request.POST, prefix='user')
        siteuser_form = SiteUserForm(request.POST, prefix='siteuser')
        # check whether they are valid:
        if user_form.is_valid() and siteuser_form.is_valid():
            user = user_form.save(commit=False) #Create user, but don't save to the database yet
            user.is_active = False
            user.set_password(user.password)
            user.save()
            user.siteuser.developer_status = siteuser_form.cleaned_data['developer_status']
            user.save()
            user_form.save_m2m() #save the many-to-many data for the form

            # Send activation email
            signer = TimestampSigner()
            key = signer.sign(user.id)
            message = 'Visit the following link to activate your account: {}/activate/{}'.format(request.get_host(), key)
            with mail.get_connection() as connection:
                mail.EmailMessage(
                    'Your activation link', message, 'admin@gamesite.fi', [user.email], connection=connection, ).send()
            return render(request, 'message.html', {'message': 'An activation link was sent to your email adress!'})
    else:
        user_form = UserForm(prefix='user')
        siteuser_form = SiteUserForm(prefix='siteuser')

    return render(request, 'registration/register.html', {'user_form': user_form, 'siteuser_form': siteuser_form})

def activate(request, key):
    try:
        signer = TimestampSigner()
        user_id = signer.unsign(key, max_age=timedelta(days=2))
        user = User.objects.get(id=user_id)

        if user.is_active == False:

gamehost/templates/add_game.html
{% extends "base.html" %}

{% block content %}

<h1>Add new game</h1>

<p>Please fill in game information</p>

<form action="/add_game/" method="post">
    {% csrf_token %}
    {% for field in game_form %}
      <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag}} {{ field }}
        {% if field.help_text %}
          <p class="help"> {{ field.help_text|safe }}</p>
        {% endif %}
      </div>
    {% endfor %}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

gamehost/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <title>{% block title %}GameSite{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="{% static 'layout.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" type='text/javascript'></script>

    {% block js-block %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                  data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Gamehost</a>
        </div>
        <div class="collapse navbar-collapse">
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-left">
            <li><a href="/purchased_games/{{ user.id }}/" id="mygames">My Games</a></li>
            <li><a href="{% url 'basket' %}" id="basket">Basket</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/accounts/profile/{{user.id}}/" id="profile">Profile</a></li>
            <li><a href="{% url 'logout' %}" id="logout">Logout</a></li>
          </ul>
          {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'login' %}" id="login">Login</a></li>
            <li><a href="/register/" id="register">Register</a></li>
            <li><a href="{% url 'social:begin' 'twitter' %}">Twitter login</a></li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block decoration %}

    {% endblock %}

    <div id="content" class="container">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

gamehost/templates/basket.html
{% extends "base.html" %}

{% block content %}
<div id="basket" class="container">
<h3> Basket </h3>
{% include "basket_contents.html" %}

{% if games %}
<button type="button" class="btn btn-primary btn-block" onclick="location.href='{% url 'checkout' %}';">Checkout</button>
{% endif %}
</div>

{% endblock %}

gamehost/templates/basket_contents.html
{% if games %}
<script>
    $(document).ready(function(){
        $(".remove").click(function() {
            $.ajax("/remove_from_basket/" + this.id + "/",
                 {success: function(res){
                     $("div#basket").html(res);
                 }});
        });
    });
</script>
<table class="table table-striped">
  <tr>
    <th class="col-xs-3">Game</th>
    <th class="col-xs-2">Price</th>
    <th class="col-xs-1"></th>
  </tr>
  {% for game in games %}
  <tr>
    <td>{{ game.name }}</td>
    <td>{{ game.price }} €</td>
    {% if modifiable %}
      <td> <button type="button" class="remove btn btn-warning btn-sm btn-block" id="{{ game.id }}">Remove</button> </td>
    {% else %}
      <td></td>
    {% endif %}
  </tr>
  {% endfor %}
  <tr>
    <th>Total</th>
    <th>{{ total }} €</th>
    <th></th>
  </tr>
</table>
{% else %}
<p class="text-info"> Basket is empty.</p>
{% endif %}

gamehost/templates/checkout.html
{% extends "base.html" %}

{% block content %}
<h3> Basket </h3>
<div id="basket">
{% include "basket_contents.html" %}
</div>

<form action="http://payments.webcourse.niksula.hut.fi/pay/" method="POST">
    <input type="hidden" name="pid" value="{{ pid }}" />
    <input type="hidden" name="sid" value="{{ sid }}" />
    <input type="hidden" name="success_url" value="{{ host }}{% url 'payment_success' %}"/>
    <input type="hidden" name="cancel_url" value="{{ host }}{% url 'payment_cancel' %}" />
    <input type="hidden" name="error_url" value="{{ host }}{% url 'payment_error' %}" />
    <input type="hidden" name="checksum" value="{{ checksum }}" />
    <input type="hidden" name="amount" value="{{ total }}" />
    <input type="hidden" name="dev" value="test" />
    <input type="submit" value="Proceed to Payment" class="btn btn-primary btn-block"/>
</form>

{% endblock %}

gamehost/templates/delete_game.html
{% block game_edits %}
  <form action="/deletegame/{{ object.id }}/" method="POST">
    {% csrf_token %}
    <p> Are you sure you want to delete {{ object }}?</p>
    <input type="submit" value="Confirm"/>
{% endblock %}

gamehost/templates/edit_game.html
{% block game_edits %}
<h3>Edit the game information</h3>

<form action="/editgame/{{ game.id }}/" method="POST">
  {% csrf_token %}
  {% for field in game_form %}
    <div class="fieldWrapper">
      {{ field.errors }}
      {{ field.label_tag }} {{ field }}
      {% if field.help_text %}
        <p class="help"> {{ field.help_text|safe }}</p>
      {% endif %}
    </div>
  {% endfor %}
  <input type="submit" value="Submit" />
</form>

{% endblock %}

gamehost/templates/game.html
{% extends "base.html" %}
{% load static %}

{% block js-block %}
  <script src="{% static 'message_protocol.js' %}" type='text/javascript'></script>
{% endblock %}

{% block content %}
  <script>
    var game = '{{ game }}';
    var user = '{{ user }}';
  </script>
  <script>
    $(document).ready(function(){
      $("#edit_game").click(function(){
        $.ajax({
          url: '/editgame/{{ game.id }}/',
          data: {'user': user, 'game': game},
          success: function(res){
            $(".game_info").html(res);
          }
        });
      });
      $("#remove_game").click(function(){
        $.ajax({
          url: '/deletegame/{{ game.id }}/',
          data: {'user': user, 'game': game},
          success: function(res){
            $(".game_info").html(res);
          }
        });
      });
      $("#add_to_basket").click(function() {
          $.ajax("/add_to_basket/{{ game.id }}/");
      });
    });
  </script>

  <section class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1> {{ game.name }} </h1>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-8">
        {% if has_purchased or game.developer == user.siteuser and user.siteuser.developer_status == 1 %}
        <iframe id="game" src={{ game.src }}></iframe>
        <p id="last_saved"></p>
        {% else %}
        <image id="img" src={{ game.thumbnail }}>
        <p class="text-info"> Price: {{ game.price }} €</p>
        <button type="button" id="add_to_basket" class="btn btn-primary">Add to Basket</button>
        {% endif %}
      </div>
      <div class="col-sm-4 highscores">
        {% include "highscore.html" %}
      </div>
    </div>
    {% if user.siteuser.developer_status == 1 and game.developer == user.siteuser %}
    <div class="row">
      <h3>Developer options</h3>
      <div class="col-sm-4">
        <a><p class="dev_op" id="edit_game">Edit game</p></a>
        <p class="dev_op">Show sales statistics</p>
        <a><p class="dev_op" id="remove_game">Remove game</p></a>
      </div>
      <div class="col-sm-6 game_info">
        {% block game_edits %}
        {% endblock %}
      </div>
    </div>
    {% endif %}
  </section>
{% endblock %}

gamehost/templates/games.html
{% block games %}
{% if games %}

{% for g in games %}
<a href="/game/{{ g.id }}/">
  <div class="row game_box">
    <h1>{{ g.name }}</h1>
    <img class="game_thumbnail right" src= {{g.thumbnail}}>
    <h3>{{ g.category }}</h3>
    <p>Price: {{ g.price }}€</p>
    <p class="developer_name"> Developer: {{ g.developer.user.username }}</p>

  </div>
</a>
{% endfor %}


{% else %}
<p> No games available. </p>
{% endif %}

{% endblock %}

gamehost/templates/highscore.html
<h3> Highscores </h3>
<table class="table table-striped">
{% for score in highscores %}
  <tr>
    <td>{{ score.score }}</td>
    <td>{{ score.player.user.username }}</td>
  </tr>
{% endfor %}
</table>

gamehost/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block js-block %}
  <script src="{% static 'search_functions.js' %}" type='text/javascript'></script>
{% endblock %}

{% block decoration %}
<section class="jumbotron">
  <div class="container">
    <div class="row text-center">
      <h2>Git Gud!</h2>
      <h3>Web Software Development</h3>
    </div>
  </div>
</section>

{% endblock %}

{% block content %}

<section class="container">
  <div class="col-sm-6" id="games_div">
    {% block games %}
    {% endblock %}
  </div>


{% block search %}
  <div class="col-sm-6">
    <h3 class="filter"> Filters </p>
    <a class="filter" id="all_filter"><p> All Games </p></a>
    <a class="filter" id="strategy_filter"><p> Strategy </p></a>
    <a class="filter" id="shooting_filter"><p> Shooting </p></a>
    <a class="filter" id="arcade_filter"><p> Arcade </p></a>
    <a class="filter" id="adventure_filter"><p> Adventure </p></a>
  </div>
{% endblock %}
</section>
{% endblock %}

gamehost/templates/message.html
{% extends "base.html" %}

{% block content %}

<p class="message">{{ message }}</p>

{% endblock %}

gamehost/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block js-block %}
  <script src="{% static 'show_hide.js' %}" type='text/javascript'></script>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/modules/exporting.js"></script>
  <script>
    'use strict'
    var a = {{ datelistj|safe }};
  </script>

{% endblock %}

{% block content %}
  <section class="container">
    <div class="row">
      <div class="col-sm-6">
        <h2> Profile: {{ user.username }}</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <p> Register date: {{ user.siteuser.registration_date }}</p>
        <p> Games purchased: {{ user.siteuser.transaction_set.count }}</p>
      </div>
    </div>
    {% if user.siteuser.developer_status %}
      <div class="row">
        <div class="col-sm-6">
          <h3> Developer information</h3>
          <!-- Might need formatting -->
          <p><a href="/add_game/">Add new game</a></p>
          <h4>Sales statistics</h4>

          <div class="gamestatsparent">
            {% for game in games %}
            <div class="gamestats">
              <h5>{{ game.name }}</h5>
              {% for gamename, value in totalSalesList.items %}
                {% if gamename == game.name %}
                <p>Total sales: {{ value }}</p>
                <p class="show_chart">Show details</p>

                <div class="chart">
                  <div id="{{ game.name }}" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                  <script src="{% static 'charts.js' %}" type="text/javascript"></script>

                  <p class="hide_chart">Hide details</p>
                </div>
                {% endif %}
              {% endfor %}



            </div>
            {% endfor %}
          </div>
          <!-- Might need formatting -->
        </div>

      </div>
      {% if user.siteuser.game_set.count > 0 %}
      <div class="row">
        <div class="col-sm-6">
          <h3> Own games </h3>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          {% for game in user.siteuser.game_set.all %}
            <div class="game_box inline">
              <a href="/game/{{ game.id }}/">
                <h1>{{ game.name }}</h1>
                <img class="game_thumbnail" src={{ game.thumbnail }}>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
    {% endif %}
  </section>
{% endblock %}

gamehost/templates/purchased_games.html
{% extends "base.html" %}

{% block content %}
  <section class="container">
    <div class="row">
      <h1> {{ user.username }}'s purchased games </h1>
    </div>
    <div class="row">
      {% for transaction in user.siteuser.get_transactions %}
        <div class="game_box inline">
          <a href="/game/{{ transaction.game.id }}/">
            <h1>{{ transaction.game.name }}</h1>
            <img class="game_thumbnail" src={{ transaction.game.thumbnail }}>
          </a>
        </div>
      {% endfor %}
    </div>
{% endblock %}